import { useNavigate } from "react-router-dom";
import { UserButton } from "@clerk/clerk-react";
import {
  Search,
  TrendingUp,
  Star,
  Users,
  ArrowRight,
  Compass,
  Sparkles,
  LayoutDashboard,
} from "lucide-react";

// MOCK DATA: Community aggregated paths
const TRENDING_PATHS = [
  {
    id: 1,
    title: "Zero to Full-Stack Next.js",
    author: "AI Curated • @dev_sarah",
    users: 1204,
    rating: 4.9,
    tags: ["React", "Node.js", "Vercel"],
    time: "8 Weeks",
  },
  {
    id: 2,
    title: "Data Science & Machine Learning",
    author: "AI Curated • @data_guru",
    users: 856,
    rating: 4.8,
    tags: ["Python", "Pandas", "PyTorch"],
    time: "12 Weeks",
  },
  {
    id: 3,
    title: "AWS Cloud Architect Fundamentals",
    author: "AI Curated • @cloud_ninja",
    users: 643,
    rating: 4.7,
    tags: ["AWS", "DevOps", "Docker"],
    time: "6 Weeks",
  },
  {
    id: 4,
    title: "UI/UX Design for Developers",
    author: "AI Curated • @design_system",
    users: 432,
    rating: 4.9,
    tags: ["Figma", "CSS", "Accessibility"],
    time: "4 Weeks",
  },
];

export default function Explore() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 flex flex-col font-sans">
      {/* NAVBAR */}
      <header className="h-16 bg-slate-900 border-b border-slate-800 flex items-center justify-between px-6 shrink-0 z-10 shadow-md">
        <div
          className="flex items-center gap-3 cursor-pointer"
          onClick={() => navigate("/")}
        >
          <div className="p-1.5 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg">
            <Sparkles size={20} className="text-slate-950" />
          </div>
          <h1 className="font-bold text-xl text-slate-100">LearnPilot</h1>
        </div>

        <nav className="hidden md:flex items-center gap-6">
          <button
            onClick={() => navigate("/dashboard")}
            className="flex items-center gap-2 text-slate-400 hover:text-emerald-400 transition-colors font-medium"
          >
            <LayoutDashboard size={18} /> My Path
          </button>
          <button className="flex items-center gap-2 text-emerald-400 font-bold">
            <Compass size={18} /> Explore Hub
          </button>
        </nav>

        <UserButton
          afterSignOutUrl="/"
          appearance={{
            elements: {
              userButtonAvatarBox:
                "w-9 h-9 border-2 border-slate-700 hover:border-emerald-500",
            },
          }}
        />
      </header>

      {/* MAIN CONTENT */}
      <main className="flex-1 p-6 md:p-12 max-w-7xl mx-auto w-full">
        {/* Header & Search */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
          <div>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-2 flex items-center gap-3">
              <Compass className="text-emerald-400" size={36} /> Explore
              Pathways
            </h2>
            <p className="text-slate-400 text-lg">
              Discover and fork learning roadmaps generated by the community.
            </p>
          </div>

          <div className="relative w-full md:w-96">
            <Search
              className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"
              size={20}
            />
            <input
              type="text"
              placeholder="Search subjects, tools, or goals..."
              className="w-full bg-slate-900 border border-slate-700 focus:border-emerald-500 rounded-xl py-3 pl-12 pr-4 text-white outline-none transition-all shadow-inner"
            />
          </div>
        </div>

        {/* Section Title */}
        <div className="flex items-center gap-2 mb-6">
          <TrendingUp className="text-purple-400" size={24} />
          <h3 className="text-2xl font-bold text-slate-200">
            Trending This Week
          </h3>
        </div>

        {/* Grid of Community Paths */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
          {TRENDING_PATHS.map((path) => (
            <div
              key={path.id}
              className="group bg-gradient-to-br from-slate-900 to-slate-800/50 border border-slate-800 hover:border-emerald-500/50 rounded-2xl p-6 transition-all duration-300 hover:shadow-[0_0_30px_rgba(16,185,129,0.1)] flex flex-col"
            >
              <div className="flex justify-between items-start mb-4">
                <span className="text-xs font-bold uppercase tracking-wider text-purple-400 bg-purple-500/10 px-3 py-1 rounded-full border border-purple-500/20">
                  {path.time}
                </span>
                <div className="flex gap-3 text-slate-400 text-sm font-medium">
                  <span className="flex items-center gap-1">
                    <Users size={16} /> {path.users}
                  </span>
                  <span className="flex items-center gap-1 text-yellow-500">
                    <Star size={16} /> {path.rating}
                  </span>
                </div>
              </div>

              <h4 className="text-2xl font-bold text-white mb-2 group-hover:text-emerald-400 transition-colors">
                {path.title}
              </h4>
              <p className="text-sm text-slate-400 mb-6">{path.author}</p>

              <div className="flex flex-wrap gap-2 mb-8">
                {path.tags.map((tag) => (
                  <span
                    key={tag}
                    className="text-xs font-semibold text-slate-300 bg-slate-950 px-2.5 py-1 rounded-md border border-slate-800"
                  >
                    {tag}
                  </span>
                ))}
              </div>

              <div className="mt-auto pt-4 border-t border-slate-800 flex justify-end">
                <button
                  onClick={() =>
                    navigate("/dashboard", { state: { goal: path.title } })
                  }
                  className="flex items-center gap-2 text-emerald-400 font-bold hover:text-emerald-300 transition-colors"
                >
                  Fork this Path{" "}
                  <ArrowRight
                    size={18}
                    className="group-hover:translate-x-1 transition-transform"
                  />
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
